insert into merchant  (id, create_date, name, lastname, birthdate) values
(nextval('merchant_id_seq'), '2021-01-01', 'David', 'Dupont', '1980-05-02'),
(nextval('merchant_id_seq'), '2021-01-02', 'Pierric', 'Duplo', '1979-10-13'),
(nextval('merchant_id_seq'), '2021-01-03', 'Sacha', 'Rasta', '1985-04-21'),
(nextval('merchant_id_seq'), '2021-01-04', 'Claire', 'Ruther', '1983-09-14'),
(nextval('merchant_id_seq'), '2021-01-05', 'Sia', 'Velaskez', '1970-12-30'),
(nextval('merchant_id_seq'), '2021-01-06', 'Tokyo', 'Astro', '1975-01-26');

insert into product (id, create_date, label, unit_price, currency, weight, height) values
(nextval('product_id_seq'), '2021-02-01', 'Drone', 1500, 'EUR', 4, 0.5),
(nextval('product_id_seq'), '2021-02-02', 'Iphone', 1200, 'EUR', 0.4, 0.1),
(nextval('product_id_seq'), '2021-02-03', 'Oeuf de pâques', 20, 'EUR', 0.3, 0.2),
(nextval('product_id_seq'), '2021-02-04', 'Tournesol', 5, 'EUR', 0.1, 0.2),
(nextval('product_id_seq'), '2021-02-05', 'Jeu de 52 carte', 10, 'EUR', 0.1, 0.1),
(nextval('product_id_seq'), '2021-02-06', 'Tarot', 15, 'EUR', 0.1, 0.1),
(nextval('product_id_seq'), '2021-02-07', 'Billet de cinéma', 10, 'EUR', 0.01, 0.01),
(nextval('product_id_seq'), '2021-02-08', 'Trottinette', 900, 'EUR', 20, 20),
(nextval('product_id_seq'), '2021-02-09', 'Sapin', 50, 'EUR', 5, 10);

insert into merchant_product (id, affiliation_id, merchant_id, product_id, affectation_date) values
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Pierric' limit 1),'_',(select id from product where label = 'Drone' limit 1)),
        (select id from merchant where name = 'Pierric' limit 1),
        (select id from product where label = 'Drone' limit 1),
        '2021-03-01'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Pierric' limit 1),'_',(select id from product where label = 'Iphone' limit 1)),
        (select id from merchant where name = 'Pierric' limit 1),
        (select id from product where label = 'Iphone' limit 1),
        '2021-03-02'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Claire' limit 1),'_',(select id from product where label = 'Sapin' limit 1)),
        (select id from merchant where name = 'Claire' limit 1),
        (select id from product where label = 'Sapin' limit 1),
        '2021-03-03'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Claire' limit 1),'_',(select id from product where label = 'Tournesol' limit 1)),
        (select id from merchant where name = 'Claire' limit 1),
        (select id from product where label = 'Tournesol' limit 1),
        '2021-03-04'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Tokyo' limit 1),'_',(select id from product where label = 'Billet de cinéma' limit 1)),
        (select id from merchant where name = 'Tokyo' limit 1),
        (select id from product where label = 'Billet de cinéma' limit 1),
        '2021-03-05'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'David' limit 1),'_',(select id from product where label = 'Drone' limit 1)),
        (select id from merchant where name = 'David' limit 1),
        (select id from product where label = 'Drone' limit 1),
        '2021-03-06'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'David' limit 1),'_',(select id from product where label = 'Trottinette' limit 1)),
        (select id from merchant where name = 'David' limit 1),
        (select id from product where label = 'Trottinette' limit 1),
        '2021-03-07'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Sacha' limit 1),'_',(select id from product where label = 'Drone' limit 1)),
        (select id from merchant where name = 'Sacha' limit 1),
        (select id from product where label = 'Drone' limit 1),
        '2021-03-08'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Sacha' limit 1),'_',(select id from product where label = 'Trottinette' limit 1)),
        (select id from merchant where name = 'Sacha' limit 1),
        (select id from product where label = 'Trottinette' limit 1),
        '2021-03-09'),
    (nextval('merchant_product_id_seq'),
        concat((select id from merchant where name = 'Sacha' limit 1),'_',(select id from product where label = 'Iphone' limit 1)),
        (select id from merchant where name = 'Sacha' limit 1),
        (select id from product where label = 'Iphone' limit 1),
        '2021-03-10');


insert into address (id, number, street, zipcode, merchant_id) values
    (nextval('address_id_seq'),1,'rue de Paris', '75011',
        (select id from merchant where name = 'Sacha' limit 1)),
    (nextval('address_id_seq'),2,'rue de Gaston', '94400',
        (select id from merchant where name = 'Sacha' limit 1)),
    (nextval('address_id_seq'),3,'rue des berges', '75001',
        (select id from merchant where name = 'Pierric' limit 1)),
    (nextval('address_id_seq'),4,'rue du marais', '92130',
        (select id from merchant where name = 'David' limit 1)),
    (nextval('address_id_seq'),5,'rue de Alpes', '92410',
        (select id from merchant where name = 'Claire' limit 1)),
    (nextval('address_id_seq'),6,'rue de cheminées', '92390',
        (select id from merchant where name = 'Sia' limit 1)),
    (nextval('address_id_seq'),7,'rue de avions', '92150',
        (select id from merchant where name = 'Sia' limit 1)),
    (nextval('address_id_seq'),8,'rue de la salsa', '91290',
        (select id from merchant where name = 'Sia' limit 1)),
    (nextval('address_id_seq'),9,'rue de Gaspard', '75020',
        (select id from merchant where name = 'Tokyo' limit 1));
